/**
 * enumerate.mjs — finding hooked mints.
 *
 * Enumeration is the hard part of this census and the honest answer is that exactly one
 * method is complete:
 *
 *   A. gpa-full          getProgramAccounts over Token-2022, every mint that has extensions.
 *                        COMPLETE by construction. Most public RPCs refuse it.
 *   B. gpa-offset-sweep  getProgramAccounts filtered on the TransferHook TLV header at a
 *                        fixed byte offset. Cheaper, still GPA. Complete only for mints
 *                        whose hook TLV lands on one of the swept offsets.
 *   C. tx-sample         Sample a program's transaction history, harvest every account key
 *                        seen, and test each one. Coverage is whatever share of traffic we
 *                        sampled, over a slot range we record exactly.
 *   D. seed-verify       Test an explicit candidate list. Coverage is the list.
 *   E. jupiter-verified  Take the Token-2022 subset of a public token list and check every
 *                        member. COMPLETE for that named population — a real denominator —
 *                        but that population is curated and is not the chain. (jupiter.mjs)
 *   F. gpa-hook-program  getProgramAccounts against a KNOWN HOOK PROGRAM, which public
 *                        endpoints do serve even though they refuse it for Token-2022, then
 *                        mine embedded pubkeys from its accounts.
 *
 * B, C, D, E and F are all PARTIAL with respect to mainnet and are labelled as such. None of
 * them can ever justify "there are N hooked mints on mainnet" — only A can. E can justify
 * "N of the M Token-2022 mints in <named list>", which is a different and weaker claim.
 */

import {
  getMultipleAccounts, getProgramAccountsOrThrow, getSignaturesForAddress,
  rpc, RpcError,
} from './rpc.mjs';
import { b58encode } from './crypto.mjs';
import {
  parseMintExtensions, parseTransferHook, parseMintBase,
  EXT_TRANSFER_HOOK, TOKEN_2022_PROGRAM, ACCOUNT_TYPE_OFFSET, TLV_START_OFFSET,
} from './tlv.mjs';

/** memcmp `bytes` are base58, so encode the raw filter bytes rather than hardcoding strings. */
export const MINT_ACCOUNT_TYPE_B58 = b58encode(Uint8Array.from([1]));

/** TLV header for TransferHook: type=14 (u16 LE), length=64 (u16 LE). */
export const TRANSFER_HOOK_TLV_HEADER = Uint8Array.from([14, 0, 64, 0]);
export const TRANSFER_HOOK_TLV_HEADER_B58 = b58encode(TRANSFER_HOOK_TLV_HEADER);

/**
 * Byte sizes of the mint-side extensions that can precede TransferHook in the TLV region.
 * Used to generate candidate offsets for method B. Fixed-size extensions only — a mint
 * carrying a variable-length extension (TokenMetadata) *before* its hook cannot be reached
 * by an offset sweep, which is one reason B is partial.
 */
export const MINT_EXTENSION_SIZES = {
  1: 108,  // TransferFeeConfig
  3: 32,   // MintCloseAuthority
  4: 65,   // ConfidentialTransferMint
  6: 1,    // DefaultAccountState
  9: 0,    // NonTransferable
  10: 24,  // InterestBearingConfig
  12: 32,  // PermanentDelegate
  16: 129, // ConfidentialTransferFeeConfig
  18: 64,  // MetadataPointer
  20: 64,  // GroupPointer
  21: 72,  // TokenGroup
  22: 64,  // GroupMemberPointer
  23: 72,  // TokenGroupMember
  25: 24,  // ScaledUiAmount
  26: 1,   // Pausable
};

/**
 * Candidate byte offsets at which a TransferHook TLV header can begin, assuming every
 * preceding extension is fixed-size. Generated by walking all subsets up to `maxDepth`
 * preceding extensions, deduplicated and sorted.
 */
export function candidateHookOffsets(maxDepth = 3) {
  const sizes = Object.values(MINT_EXTENSION_SIZES).map((s) => s + 4); // +4 TLV header
  const offsets = new Set([TLV_START_OFFSET]);
  let frontier = [TLV_START_OFFSET];
  for (let depth = 0; depth < maxDepth; depth++) {
    const next = [];
    for (const base of frontier) {
      for (const s of sizes) {
        const o = base + s;
        if (!offsets.has(o)) { offsets.add(o); next.push(o); }
      }
    }
    frontier = next;
  }
  return [...offsets].sort((a, b) => a - b);
}

// ---------------------------------------------------------------------------
// Classification
// ---------------------------------------------------------------------------

/**
 * Decide what an account is, from its raw RPC value.
 *
 * Returns one of:
 *   { kind: 'absent' }              account does not exist
 *   { kind: 'not-token-2022' }      owned by another program
 *   { kind: 'not-a-mint' }          Token-2022 but a token account / multisig
 *   { kind: 'mint', hooked: false } Token-2022 mint with no TransferHook extension
 *   { kind: 'mint', hooked: true, hook, ... }
 *
 * Returns null only when the bytes could not be parsed at all — an unmeasured cell.
 */
export function classifyAccount(value) {
  if (!value) return { kind: 'absent' };
  if (value.owner !== TOKEN_2022_PROGRAM) return { kind: 'not-token-2022', owner: value.owner };

  let data;
  try {
    data = Buffer.from(value.data[0], 'base64');
  } catch {
    return null;
  }

  const parsed = parseMintExtensions(data);
  if (!parsed) return { kind: 'not-a-mint' };

  const base = parseMintBase(data);
  if (!base) return null;

  const hookEntry = parsed.entries.find((e) => e.type === EXT_TRANSFER_HOOK);
  if (!hookEntry) {
    return {
      kind: 'mint', hooked: false, base, extensions: parsed.entries,
      tlvTruncated: parsed.truncated, dataLength: data.length,
    };
  }

  const hook = parseTransferHook(hookEntry.value);
  return {
    kind: 'mint', hooked: true, base, hook, extensions: parsed.entries,
    hookTlvOffset: hookEntry.offset - 4,
    tlvTruncated: parsed.truncated, dataLength: data.length,
  };
}

// ---------------------------------------------------------------------------
// Candidate testing (shared by every method)
// ---------------------------------------------------------------------------

/**
 * Fetch and classify a set of addresses, using the cache and batching 100 per RPC call.
 * Returns `{ results, fetched, cached, failed }`. Addresses whose fetch failed land in
 * `failed` and are NOT recorded as "no hook" — an unfetched account is unmeasured.
 */
export async function checkCandidates(addresses, { cache, log = () => {}, batchSize = 100 } = {}) {
  const unique = [...new Set(addresses)];
  const results = new Map();
  const failed = [];
  let fetched = 0;
  let cachedCount = 0;

  const toFetch = [];
  for (const addr of unique) {
    const hit = cache ? await cache.getAccount(addr) : null;
    if (hit) {
      cachedCount++;
      results.set(addr, { classification: classifyAccount(hit.value), slot: hit.slot, fromCache: true });
    } else {
      toFetch.push(addr);
    }
  }

  for (let i = 0; i < toFetch.length; i += batchSize) {
    const batch = toFetch.slice(i, i + batchSize);
    const res = await getMultipleAccounts(batch);
    if (!res) {
      failed.push(...batch);
      log(`  batch of ${batch.length} failed; recorded as unmeasured`);
      continue;
    }
    for (let j = 0; j < batch.length; j++) {
      const addr = batch[j];
      const value = res.values[j] ?? null;
      if (cache) await cache.putAccount(addr, value, res.slot);
      results.set(addr, { classification: classifyAccount(value), slot: res.slot, fromCache: false });
      fetched++;
    }
    log(`  checked ${Math.min(i + batchSize, toFetch.length)}/${toFetch.length} candidates`);
  }

  return { results, fetched, cached: cachedCount, failed };
}

// ---------------------------------------------------------------------------
// Method A / B — getProgramAccounts
// ---------------------------------------------------------------------------

/**
 * Probe whether this endpoint will serve getProgramAccounts on Token-2022 at all.
 * Returns `{ available: true }` or `{ available: false, reason, refusal }`.
 * We ask for a zero-length dataSlice so the probe is as cheap as the endpoint allows.
 */
export async function probeGpa() {
  try {
    await getProgramAccountsOrThrow(TOKEN_2022_PROGRAM, {
      dataSlice: { offset: 0, length: 0 },
      filters: [
        { memcmp: { offset: ACCOUNT_TYPE_OFFSET, bytes: MINT_ACCOUNT_TYPE_B58 } },
        { memcmp: { offset: TLV_START_OFFSET, bytes: TRANSFER_HOOK_TLV_HEADER_B58 } },
      ],
    }, { timeoutMs: 30_000, retries: 0 });
    return { available: true };
  } catch (err) {
    return {
      available: false,
      reason: err.message,
      refusal: err instanceof RpcError ? err.isRefusal : false,
    };
  }
}

/**
 * Method A: every Token-2022 mint that carries extensions, parsed locally for a hook.
 * This is the only complete method. Returns null if the endpoint refuses it.
 */
export async function gpaFullMintScan({ cache, log = () => {} } = {}) {
  log('[gpa-full] requesting every Token-2022 mint with extensions...');
  let accounts;
  try {
    accounts = await getProgramAccountsOrThrow(TOKEN_2022_PROGRAM, {
      filters: [{ memcmp: { offset: ACCOUNT_TYPE_OFFSET, bytes: MINT_ACCOUNT_TYPE_B58 } }],
    }, { timeoutMs: 300_000 });
  } catch (err) {
    log(`[gpa-full] unavailable: ${err.message}`);
    return null;
  }

  const hooked = [];
  let scanned = 0;
  for (const acc of accounts) {
    scanned++;
    const value = acc.account;
    if (cache) await cache.putAccount(acc.pubkey, value, null);
    const c = classifyAccount(value);
    if (c?.kind === 'mint' && c.hooked) hooked.push({ mint: acc.pubkey, classification: c });
  }
  log(`[gpa-full] scanned ${scanned} mints, ${hooked.length} carry a TransferHook`);
  return { method: 'gpa-full', complete: true, scanned, hooked };
}

/**
 * Method B: one GPA per candidate TLV offset, filtered to the TransferHook header bytes.
 * Complete only for mints whose hook sits at a swept offset; the swept list is returned
 * so the output can state exactly what was covered.
 */
export async function gpaOffsetSweep({ cache, maxDepth = 2, log = () => {} } = {}) {
  const offsets = candidateHookOffsets(maxDepth);
  log(`[gpa-sweep] sweeping ${offsets.length} candidate hook offsets`);

  const hooked = [];
  const offsetsCovered = [];
  const offsetsFailed = [];

  for (const offset of offsets) {
    try {
      const accounts = await getProgramAccountsOrThrow(TOKEN_2022_PROGRAM, {
        filters: [
          { memcmp: { offset: ACCOUNT_TYPE_OFFSET, bytes: MINT_ACCOUNT_TYPE_B58 } },
          { memcmp: { offset, bytes: TRANSFER_HOOK_TLV_HEADER_B58 } },
        ],
      }, { timeoutMs: 120_000, retries: 1 });
      offsetsCovered.push(offset);
      for (const acc of accounts) {
        if (cache) await cache.putAccount(acc.pubkey, acc.account, null);
        const c = classifyAccount(acc.account);
        if (c?.kind === 'mint' && c.hooked) hooked.push({ mint: acc.pubkey, classification: c });
      }
      if (accounts.length) log(`[gpa-sweep] offset ${offset}: ${accounts.length} hits`);
    } catch (err) {
      offsetsFailed.push({ offset, reason: err.message });
      if (err instanceof RpcError && err.isRefusal) {
        log(`[gpa-sweep] endpoint refuses GPA; aborting sweep`);
        break;
      }
    }
  }

  if (offsetsCovered.length === 0) return null;
  return {
    method: 'gpa-offset-sweep',
    complete: false,
    offsetsSwept: offsetsCovered,
    offsetsFailed,
    hooked: dedupeByMint(hooked),
  };
}

function dedupeByMint(rows) {
  const seen = new Map();
  for (const r of rows) if (!seen.has(r.mint)) seen.set(r.mint, r);
  return [...seen.values()];
}

// ---------------------------------------------------------------------------
// Method E — getProgramAccounts against a hook program (not Token-2022)
// ---------------------------------------------------------------------------

/**
 * Slide a 32-byte window across an account's data and return every window that could be a
 * pubkey. A hook program's own accounts (per-mint config, whitelists, position records)
 * almost always embed the mint they belong to, but at an offset that varies by program, so
 * we do not guess the layout — we take every alignment and let the on-chain check decide.
 *
 * All-zero windows are skipped: they decode to the System Program and are never a mint.
 */
export function pubkeyWindows(data, { stride = 1 } = {}) {
  const b = Buffer.isBuffer(data) ? data : Buffer.from(data);
  const out = new Set();
  for (let o = 0; o + 32 <= b.length; o += stride) {
    const w = b.subarray(o, o + 32);
    let allZero = true;
    for (let i = 0; i < 32; i++) if (w[i] !== 0) { allZero = false; break; }
    if (allZero) continue;
    out.add(b58encode(w));
  }
  return out;
}

/**
 * Enumerate a hook program's accounts and harvest embedded pubkey candidates.
 *
 * Public endpoints refuse getProgramAccounts on Token-2022 but DO serve it for ordinary
 * custom programs, so this works where the Token-2022 scan does not. It enumerates the
 * accounts of ONE hook program — complete for that program's account set, and silent about
 * every mint whose hook program stores no reference to it.
 *
 * Large programs hit `-32012 scan aborted: accumulated scan results exceeded the limit`;
 * that is reported, not swallowed.
 */
export async function gpaHookProgramCandidates(hookProgramId, {
  cache, stride = 1, maxCandidates = 20_000, dataSliceLength = 512, log = () => {},
} = {}) {
  const cacheKey = `gpa-hook:${hookProgramId}`;
  let accounts = null;

  if (cache) {
    const hit = await cache.getRpc(cacheKey);
    if (hit) accounts = hit.result;
  }

  if (accounts === null) {
    try {
      // A hook program can own a lot of data — one of these returned a response large
      // enough to blow Node's 512MB max string length while parsing. Cap each account
      // with a dataSlice: we only need the leading bytes to mine embedded pubkeys, and
      // an unbounded fetch fails outright instead of returning less.
      accounts = await getProgramAccountsOrThrow(hookProgramId, {
        dataSlice: { offset: 0, length: dataSliceLength },
      }, { timeoutMs: 120_000, retries: 1 });
      if (cache) await cache.putRpc(cacheKey, accounts);
    } catch (err) {
      const scanLimit = /-32012|scan aborted|exceeded the limit/i.test(err.message);
      const tooLarge = /longer than|0x1fffffe8|allowance|413/i.test(err.message);
      log(`[gpa-hook] ${hookProgramId}: ${scanLimit ? 'scan limit exceeded' : tooLarge ? 'response too large / quota' : 'unavailable'} — ${err.message}`);
      return {
        hookProgramId, available: false, scanLimitExceeded: scanLimit, responseTooLarge: tooLarge,
        reason: err.message, accountsSeen: 0, candidates: [], truncated: false,
      };
    }
  }

  const candidates = new Set();
  let truncated = false;
  for (const acc of accounts) {
    let data;
    try { data = Buffer.from(acc.account.data[0], 'base64'); } catch { continue; }
    for (const k of pubkeyWindows(data, { stride })) {
      if (candidates.size >= maxCandidates) { truncated = true; break; }
      candidates.add(k);
    }
    if (truncated) break;
  }

  log(`[gpa-hook] ${hookProgramId}: ${accounts.length} program accounts, ${candidates.size} distinct pubkey candidates${truncated ? ' (capped)' : ''}`);

  return {
    hookProgramId,
    available: true,
    scanLimitExceeded: false,
    accountsSeen: accounts.length,
    candidates: [...candidates],
    truncated,
  };
}

// ---------------------------------------------------------------------------
// Method C — transaction sampling
// ---------------------------------------------------------------------------

/**
 * Pull every account key referenced by a transaction, including addresses loaded from
 * lookup tables, so a hooked mint touched via an ALT is not missed.
 */
export function accountKeysOf(tx) {
  const keys = [];
  const msgKeys = tx?.transaction?.message?.accountKeys ?? [];
  for (const k of msgKeys) keys.push(typeof k === 'string' ? k : k?.pubkey);
  const loaded = tx?.meta?.loadedAddresses;
  if (loaded) {
    for (const k of loaded.writable ?? []) keys.push(k);
    for (const k of loaded.readonly ?? []) keys.push(k);
  }
  return keys.filter((k) => typeof k === 'string');
}

/**
 * Sample a program's transaction history and return every distinct account key seen,
 * plus the exact slot range covered — that range is what makes the partiality checkable.
 */
export async function sampleProgramTransactions(programId, {
  maxSignatures = 1000,
  maxTransactions = 200,
  cache,
  refreshSignatures = false,
  log = () => {},
} = {}) {
  const signatures = [];
  let before = null;

  while (signatures.length < maxSignatures) {
    const limit = Math.min(1000, maxSignatures - signatures.length);
    // Signature pages are cached too. Without this a re-run would walk a *different*
    // window of history, so the dataset could not be reproduced from the cache and every
    // re-run would miss the transaction cache entirely.
    const cacheKey = `sigs:${programId}:${limit}:${before ?? 'head'}`;
    let page = null;
    if (!refreshSignatures && cache) {
      const hit = await cache.getRpc(cacheKey);
      if (hit) page = hit.result;
    }
    if (page === null) {
      page = await getSignaturesForAddress(programId, { limit, before });
      if (page && cache) await cache.putRpc(cacheKey, page);
    }
    if (!page || page.length === 0) break;
    signatures.push(...page);
    before = page[page.length - 1].signature;
    if (page.length < 1000) break;
  }

  if (signatures.length === 0) {
    log(`[tx-sample] ${programId}: no signature history returned`);
    return {
      programId, signaturesSeen: 0, transactionsFetched: 0,
      slotRange: null, accountKeys: [], failedTransactions: 0,
    };
  }

  const slots = signatures.map((s) => s.slot).filter((s) => typeof s === 'number');
  const slotRange = slots.length ? { min: Math.min(...slots), max: Math.max(...slots) } : null;

  // Sample evenly across the signature window rather than taking only the newest,
  // so the harvest is not dominated by one busy minute.
  const step = Math.max(1, Math.floor(signatures.length / maxTransactions));
  const picked = [];
  for (let i = 0; i < signatures.length && picked.length < maxTransactions; i += step) {
    picked.push(signatures[i]);
  }

  const accountKeys = new Set();
  let failed = 0;
  let fetchedCount = 0;

  for (const sig of picked) {
    const cacheKey = `tx:${sig.signature}`;
    let tx = null;
    const hit = cache ? await cache.getRpc(cacheKey) : null;
    if (hit) {
      tx = hit.result;
    } else {
      try {
        tx = await rpc('getTransaction', [sig.signature, {
          commitment: 'confirmed', maxSupportedTransactionVersion: 0, encoding: 'jsonParsed',
        }], { timeoutMs: 30_000 });
        if (cache) await cache.putRpc(cacheKey, tx);
        fetchedCount++;
      } catch (err) {
        failed++;
        if (err instanceof RpcError && err.isRefusal) {
          log(`[tx-sample] endpoint refuses getTransaction: ${err.message}`);
          break;
        }
        continue;
      }
    }
    if (!tx) { failed++; continue; }
    for (const k of accountKeysOf(tx)) accountKeys.add(k);
  }

  log(`[tx-sample] ${programId}: ${signatures.length} sigs, ${picked.length} txs sampled, ` +
      `${accountKeys.size} distinct accounts, ${failed} tx fetch failures`);

  return {
    programId,
    signaturesSeen: signatures.length,
    transactionsSampled: picked.length,
    transactionsFetched: fetchedCount,
    failedTransactions: failed,
    slotRange,
    accountKeys: [...accountKeys],
  };
}
